import type { SessionContract, SessionEvent } from "./session-types";

export const demoContract: SessionContract = {
  id: "edge-qoe-042",
  name: "Edge routing policy · QoE validation",
  objective:
    "Validate whether a new edge-routing policy improves video QoE under constrained bandwidth without increasing packet loss.",
  expectedSteps: [
    "Baseline QoE test",
    "Deploy routing config",
    "Health checks",
    "QoE validation rerun",
    "Baseline comparison",
    "Recommendation",
  ],
  successCriteria: [
    { id: "qoe", label: "QoE score", threshold: "+8% vs baseline" },
    { id: "loss", label: "Packet loss", threshold: "≤ 1.2%" },
    { id: "coverage", label: "Test coverage", threshold: "3 bandwidth tiers" },
  ],
};

export const demoEvents: SessionEvent[] = [
  {
    id: "evt-01",
    timestamp: "09:02:14",
    elapsedMinutes: 0,
    kind: "milestone",
    title: "Baseline QoE test completed",
    detail: "QoE 71.4 · packet loss 0.8% · all bandwidth tiers captured.",
    source: "qoe-suite",
    stepIndex: 0,
    outcome: "success",
    meaningfulProgress: true,
    evidence: ["baseline:qoe=71.4", "baseline:packet_loss=0.8%"],
  },
  {
    id: "evt-02",
    timestamp: "09:08:41",
    elapsedMinutes: 6,
    kind: "change",
    title: "Routing policy changed",
    detail: "Policy edge-route-v18 applied to the constrained-bandwidth cohort.",
    source: "config-service",
    stepIndex: 1,
    outcome: "success",
    meaningfulProgress: true,
    evidence: ["config:edge-route-v18", "cohort:constrained-bandwidth"],
  },
  {
    id: "evt-03",
    timestamp: "09:11:08",
    elapsedMinutes: 9,
    kind: "milestone",
    title: "Deployment completed",
    detail: "12/12 edge nodes updated successfully; rollout stable.",
    source: "deploy-controller",
    outcome: "success",
    meaningfulProgress: true,
    expectedWait: true,
    evidence: ["deployment:12/12", "rollout:error_rate=0%"],
  },
  {
    id: "evt-04",
    timestamp: "09:15:32",
    elapsedMinutes: 13,
    kind: "check",
    title: "Health checks passed",
    detail: "Availability, CPU, route convergence and edge probes are healthy.",
    source: "edge-health",
    stepIndex: 2,
    outcome: "success",
    meaningfulProgress: true,
    evidence: ["health:24/24", "route_convergence:38s"],
  },
  {
    id: "evt-05",
    timestamp: "09:23:10",
    elapsedMinutes: 21,
    kind: "poll",
    title: "Deployment status polled",
    detail: "Rollout remains healthy. No validation run has been scheduled.",
    source: "deploy-controller",
    outcome: "neutral",
    meaningfulProgress: false,
    expectedWait: true,
    evidence: ["deployment:stable", "qoe_run:none"],
  },
  {
    id: "evt-06",
    timestamp: "09:31:16",
    elapsedMinutes: 29,
    kind: "poll",
    title: "Deployment status polled again",
    detail: "Infrastructure is still healthy; objective evidence remains unchanged.",
    source: "deploy-controller",
    outcome: "warning",
    meaningfulProgress: false,
    evidence: ["deployment:stable", "evidence_age:16m"],
  },
  {
    id: "evt-07",
    timestamp: "09:39:44",
    elapsedMinutes: 37,
    kind: "clock",
    title: "Missing follow-through detected",
    detail: "The next contracted step has not started 24 minutes after health checks passed.",
    source: "session-steward",
    outcome: "warning",
    meaningfulProgress: false,
    evidence: ["expected:qoe-validation", "observed:deployment-poll", "gap:24m"],
  },
  {
    id: "evt-08",
    timestamp: "09:43:02",
    elapsedMinutes: 41,
    kind: "validation",
    title: "Low-bandwidth QoE validation started",
    detail: "Validation suite launched across 1, 2.5 and 5 Mbps tiers.",
    source: "qoe-suite",
    stepIndex: 3,
    outcome: "success",
    meaningfulProgress: true,
    evidence: ["run:qoe-884", "tiers:1/2.5/5Mbps"],
  },
  {
    id: "evt-09",
    timestamp: "09:52:27",
    elapsedMinutes: 50,
    kind: "validation",
    title: "Validation suite passed",
    detail: "QoE improved to 79.2 (+10.9%); packet loss remained at 0.9%.",
    source: "qoe-suite",
    outcome: "success",
    meaningfulProgress: true,
    evidence: ["qoe:79.2", "delta:+10.9%", "packet_loss:0.9%"],
  },
  {
    id: "evt-10",
    timestamp: "09:55:11",
    elapsedMinutes: 53,
    kind: "analysis",
    title: "Baseline comparison completed",
    detail: "All success criteria met. Recommendation: promote to a 25% traffic cohort.",
    source: "session-steward",
    stepIndex: 4,
    outcome: "success",
    meaningfulProgress: true,
    evidence: ["criteria:3/3", "recommendation:promote-25%"],
  },
];
